Updates

diff --git a/.local/bin/worktree-create b/.local/bin/worktree-create
--- a/.local/bin/worktree-create
+++ b/.local/bin/worktree-create
@@ -1,18 +1,18 @@
 #!/usr/bin/env bash
 
 find_git_root() {
-	local dir="$PWD" # Start from the current working directory
+  local dir="$PWD" # Start from the current working directory
 
-	while [ "$dir" != "$HOME" ]; do
-		if [ -d "$dir/.git" ] && [ -f "$dir/.git/HEAD" ]; then
-			echo "$dir"
-			return 0
-		fi
-		dir=$(dirname "$dir") # Move up one level in the directory tree
-	done
+  while [ "$dir" != "$HOME" ]; do
+    if [ -d "$dir/.git" ] && [ -f "$dir/.git/HEAD" ]; then
+      echo "$dir"
+      return 0
+    fi
+    dir=$(dirname "$dir") # Move up one level in the directory tree
+  done
 
-	echo "No .git directory with HEAD file found"
-	exit 1
+  echo "No .git directory with HEAD file found"
+  exit 1
 }
 
 # Confirm git repo and return root dir
@@ -31,3 +31,6 @@ source_branch="${source_input:-$default_branch}"
 
 # Create worktree with constructed path
 git worktree add -b "$branch_name" "$git_root/$branch_name" "$source_branch"
+
+# cd to the new worktree, Note: could add an arg to skip this
+cd "$git_root/$branch_name" || echo "Failed to CD"
